### PR TITLE
Optionally set Mime-type

### PR DESCRIPTION
**Pull request by tommed**
Completed following work with passing unit test:

1. Mime type can now be set when uploading file ([ticket](https://github.com/step-up-labs/firebase-storage-dotnet/issues/15))
2. Fix bug with `TimeSpan` being compared to a `null` when it's a value type

### CODE REVIEW

**Comment by bezysoftware** [comment]
Hi, I went over the PR and it looks good. Just one small thing - the tests shouldn't really be called "UnitTests", but rather IntergrationTests. Perhaps Tests for the solution and IntegrationTests for the csproj. 
If you could just rename those, I will then merge the PR

**Comment by tommed** [comment]
Hi there, not too familiar with the PR process with forks, but I believe that rename should now be in the same PR?

**Comment by bezysoftware** [comment]
Yep, that's fine. Thanks for the contribution!

**Comment by tommed** [comment]
Pleasure was mine. Looking forward to the updated nuget package!

**Pull request merged**
